# Generated by Django 2.1.15 on 2021-06-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'carrera', 'verbose_name_plural': 'carreras'},
        ),
        migrations.AlterModelOptions(
            name='coordinador',
            options={'verbose_name': 'coordinador', 'verbose_name_plural': 'coordinadores'},
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
