# Generated by Django 2.1.15 on 2021-06-07 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_auto_20210607_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('semestre', models.IntegerField(default=1)),
                ('carrera', models.ForeignKey(on_delete=True, to='usuarios.Carrera')),
                ('usuario', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='Carga_academica_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=True, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'carga_academica_alumno',
                'verbose_name_plural': 'carga_academica_alumnos',
            },
        ),
        migrations.CreateModel(
            name='Detalle_carga_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_academica_alumno', models.ForeignKey(on_delete=True, to='Alumno.Carga_academica_alumno')),
                ('materia_ca', models.ForeignKey(on_delete=True, to='Alumno.Alumno')),
            ],
            options={
                'verbose_name': 'detalle_carga_alumno',
                'verbose_name_plural': 'detalles_carga_alumno',
            },
        ),
    ]
