# Generated by Django 2.1.15 on 2021-06-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
    ]
