# Generated by Django 2.1.15 on 2021-06-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materia', '0005_unidad'),
        ('Alumno', '0003_auto_20210607_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.SmallIntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=True, to='Alumno.Alumno')),
                ('unidad', models.ForeignKey(on_delete=True, to='Materia.Unidad')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
