# Generated by Django 2.1.15 on 2021-06-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materias_carga_academica',
            options={'verbose_name': 'Materia carga academica', 'verbose_name_plural': 'Materias carga academica'},
        ),
        migrations.AlterField(
            model_name='materia',
            name='hora_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='materia',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
