# Generated by Django 2.1.15 on 2021-06-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210607_1146'),
        ('Materia', '0003_auto_20210607_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias_carga_academica',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=True, to='usuarios.Carrera'),
            preserve_default=False,
        ),
    ]
